#!/sbin/sh

busybox ln -s -f busybox [
busybox ln -s -f busybox [[
busybox ln -s -f busybox adjtimex
busybox ln -s -f busybox arp
busybox ln -s -f busybox ash
busybox ln -s -f busybox awk
busybox ln -s -f busybox base64
busybox ln -s -f busybox basename
busybox ln -s -f busybox bbconfig
busybox ln -s -f busybox blkid
busybox ln -s -f busybox blockdev
busybox ln -s -f busybox brctl
busybox ln -s -f busybox bunzip2
busybox ln -s -f busybox bzcat
busybox ln -s -f busybox bzip2
busybox ln -s -f busybox cal
busybox ln -s -f busybox cat
busybox ln -s -f busybox catv
busybox ln -s -f busybox chattr
busybox ln -s -f busybox chgrp
busybox ln -s -f busybox chmod
busybox ln -s -f busybox chown
busybox ln -s -f busybox chroot
busybox ln -s -f busybox clear
busybox ln -s -f busybox cmp
busybox ln -s -f busybox comm
busybox ln -s -f busybox cp
busybox ln -s -f busybox cpio
busybox ln -s -f busybox crond
busybox ln -s -f busybox crontab
busybox ln -s -f busybox cut
busybox ln -s -f busybox date
busybox ln -s -f busybox dc
busybox ln -s -f busybox dd
busybox ln -s -f busybox depmod
busybox ln -s -f busybox devmem
busybox ln -s -f busybox df
busybox ln -s -f busybox diff
busybox ln -s -f busybox dirname
busybox ln -s -f busybox dmesg
busybox ln -s -f busybox dnsd
busybox ln -s -f busybox dos2unix
busybox ln -s -f busybox du
busybox ln -s -f busybox echo
busybox ln -s -f busybox ed
busybox ln -s -f busybox egrep
busybox ln -s -f busybox env
busybox ln -s -f busybox expand
busybox ln -s -f busybox expr
busybox ln -s -f busybox false
busybox ln -s -f busybox fbsplash
busybox ln -s -f busybox fdisk
busybox ln -s -f busybox fgrep
busybox ln -s -f busybox find
busybox ln -s -f busybox flash_lock
busybox ln -s -f busybox flash_unlock
busybox ln -s -f busybox flashcp
busybox ln -s -f busybox flock
busybox ln -s -f busybox fold
busybox ln -s -f busybox free
busybox ln -s -f busybox freeramdisk
busybox ln -s -f busybox fsync
busybox ln -s -f busybox ftpget
busybox ln -s -f busybox ftpput
busybox ln -s -f busybox fuser
busybox ln -s -f busybox getopt
busybox ln -s -f busybox grep
busybox ln -s -f busybox groups
busybox ln -s -f busybox halt
busybox ln -s -f busybox head
busybox ln -s -f busybox hexdump
busybox ln -s -f busybox id
busybox ln -s -f busybox ifconfig
busybox ln -s -f busybox inetd
busybox ln -s -f busybox insmod
busybox ln -s -f busybox install
busybox ln -s -f busybox ionice
busybox ln -s -f busybox iostat
busybox ln -s -f busybox ip
busybox ln -s -f busybox kill
busybox ln -s -f busybox killall
busybox ln -s -f busybox killall5
busybox ln -s -f busybox length
busybox ln -s -f busybox less
busybox ln -s -f busybox ln
busybox ln -s -f busybox losetup
busybox ln -s -f busybox ls
busybox ln -s -f busybox lsattr
busybox ln -s -f busybox lsmod
busybox ln -s -f busybox lsof
busybox ln -s -f busybox lsusb
busybox ln -s -f busybox lzcat
busybox ln -s -f busybox lzma
busybox ln -s -f busybox lzop
busybox ln -s -f busybox lzopcat
busybox ln -s -f busybox man
busybox ln -s -f busybox md5sum
busybox ln -s -f busybox mesg
busybox ln -s -f busybox mkdir
busybox ln -s -f busybox mkdosfs
busybox ln -s -f busybox mke2fs
busybox ln -s -f busybox mkfifo
busybox ln -s -f busybox mkfs.ext2
busybox ln -s -f busybox mkfs.vfat
busybox ln -s -f busybox mknod
busybox ln -s -f busybox mkswap
busybox ln -s -f busybox mktemp
busybox ln -s -f busybox modinfo
busybox ln -s -f busybox modprobe
busybox ln -s -f busybox more
busybox ln -s -f busybox mount
busybox ln -s -f busybox mountpoint
busybox ln -s -f busybox mpstat
busybox ln -s -f busybox mv
busybox ln -s -f busybox nanddump
busybox ln -s -f busybox nandwrite
busybox ln -s -f busybox nc
busybox ln -s -f busybox netstat
busybox ln -s -f busybox nice
busybox ln -s -f busybox nohup
busybox ln -s -f busybox nslookup
busybox ln -s -f busybox ntpd
busybox ln -s -f busybox od
busybox ln -s -f busybox patch
busybox ln -s -f busybox pgrep
busybox ln -s -f busybox pidof
busybox ln -s -f busybox ping
busybox ln -s -f busybox pipe_progress
busybox ln -s -f busybox pkill
busybox ln -s -f busybox pmap
busybox ln -s -f busybox poweroff
busybox ln -s -f busybox printenv
busybox ln -s -f busybox printf
busybox ln -s -f busybox ps
busybox ln -s -f busybox pstree
busybox ln -s -f busybox pwd
busybox ln -s -f busybox pwdx
busybox ln -s -f busybox rdev
busybox ln -s -f busybox readlink
busybox ln -s -f busybox realpath
busybox ln -s -f busybox reboot
busybox ln -s -f busybox renice
busybox ln -s -f busybox reset
busybox ln -s -f busybox resize
busybox ln -s -f busybox rev
busybox ln -s -f busybox rm
busybox ln -s -f busybox rmdir
busybox ln -s -f busybox rmmod
busybox ln -s -f busybox route
busybox ln -s -f busybox run-parts
busybox ln -s -f busybox rx
busybox ln -s -f busybox sed
busybox ln -s -f busybox seq
busybox ln -s -f busybox setconsole
busybox ln -s -f busybox setserial
busybox ln -s -f busybox setsid
busybox ln -s -f busybox sh
busybox ln -s -f busybox sha1sum
busybox ln -s -f busybox sha256sum
busybox ln -s -f busybox sha512sum
busybox ln -s -f busybox sleep
busybox ln -s -f busybox sort
busybox ln -s -f busybox split
busybox ln -s -f busybox stat
busybox ln -s -f busybox strings
busybox ln -s -f busybox stty
busybox ln -s -f busybox sum
busybox ln -s -f busybox swapoff
busybox ln -s -f busybox swapon
busybox ln -s -f busybox sync
busybox ln -s -f busybox sysctl
busybox ln -s -f busybox tac
busybox ln -s -f busybox tail
busybox ln -s -f busybox tar
busybox ln -s -f busybox taskset
busybox ln -s -f busybox tee
busybox ln -s -f busybox telnet
busybox ln -s -f busybox telnetd
busybox ln -s -f busybox test
busybox ln -s -f busybox tftp
busybox ln -s -f busybox tftpd
busybox ln -s -f busybox time
busybox ln -s -f busybox timeout
busybox ln -s -f busybox top
busybox ln -s -f busybox touch
busybox ln -s -f busybox tr
busybox ln -s -f busybox traceroute
busybox ln -s -f busybox true
busybox ln -s -f busybox ttysize
busybox ln -s -f busybox umount
busybox ln -s -f busybox uname
busybox ln -s -f busybox uncompress
busybox ln -s -f busybox unexpand
busybox ln -s -f busybox uniq
busybox ln -s -f busybox unix2dos
busybox ln -s -f busybox unlzma
busybox ln -s -f busybox unlzop
busybox ln -s -f busybox unxz
busybox ln -s -f busybox unzip
busybox ln -s -f busybox uptime
busybox ln -s -f busybox usleep
busybox ln -s -f busybox uudecode
busybox ln -s -f busybox uuencode
busybox ln -s -f busybox vi
busybox ln -s -f busybox watch
busybox ln -s -f busybox wc
busybox ln -s -f busybox wget
busybox ln -s -f busybox which
busybox ln -s -f busybox whoami
busybox ln -s -f busybox xargs
busybox ln -s -f busybox xz
busybox ln -s -f busybox xzcat
busybox ln -s -f busybox yes
busybox ln -s -f busybox zcat

busybox ln -s -f pigz unpigz
busybox ln -s -f unpigz gunzip
busybox ln -s -f pigz gzip
busybox ln -s -f ../init ueventd
